
services:
  first-look:
    build:
      context: ./first-look
    ports:
      - "3001:3000"

  fastapi-backend:
    build:
      context: ./fastapi-backend
    ports:
      - "8001:8001"
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - FROM_PASSWORD=${FROM_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

    volumes:
      - ./.env:/app/.env
    depends_on:
      - mysql
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8001"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
