apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-apercu
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-apercu
  project: apercu
  config: prd
  managedSecret:
    name: apercu-backend-secret
    namespace: default
    type: Opaque
