apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/ap-fe
    newTag: 31f3f721fcec3b6f2c2ceb8d1cde8f6e2a7b2fee
    newName: jeanmichelbb/ap-fe
  - name: jeanmichelbb/ap-be
    newTag: 31f3f721fcec3b6f2c2ceb8d1cde8f6e2a7b2fee
    newName: jeanmichelbb/ap-be
