apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/ap-fe
    newTag: 7fec0ec254686db2ca538b850ae0e7f3e0b86afe
    newName: jeanmichelbb/ap-fe
  - name: jeanmichelbb/ap-be
    newTag: e3c8298d712ff1074ddba03cfc2c86bdb6d71a06
    newName: jeanmichelbb/ap-be
