apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/ap-fe
    newTag: fae7c17c45b74bd6e5b9cbd4f12147692e52a9a6
    newName: jeanmichelbb/ap-fe
  - name: jeanmichelbb/ap-be
    newTag: fae7c17c45b74bd6e5b9cbd4f12147692e52a9a6
    newName: jeanmichelbb/ap-be
