name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./fastapi-backend
          file: ./fastapi-backend/Dockerfile
          push: true
          tags: |
            jeanmichelbb/ap-be:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./first-look
          file: ./first-look/Dockerfile
          push: true
          tags: |
            jeanmichelbb/ap-fe:latest